title: Imlauer A.
iconURL: assets/default-icon.png
#theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  github: imlauera

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
#hyvor_talk_website_id: 14
#google_analytics: UA-NNNNNNNN-N
